# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: "Default"

variables:
  buildConfiguration: 'Release'
  versionMajor: 1
  versionMinor: 0
  versionPatch: $[counter(variables['versionPatch'], 0)]
  nugetPackageVersion: '$(versionMajor).$(versionMinor).$(versionPatch)'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'nugetPackageVersion'
    buildProperties: 'PackageVersion=$(nugetPackageVersion)'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: 'push'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'lab-tst'  # Replace this with your Azure DevOps Artifact feed name
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    allowPackageConflicts: true